### ISSUE TITLE
Invalid checksum for VirtualBox.ExtensionPack v5.1.10

### ISSUE THREAD

**Issue by pyhedgehog** [michaelray/ChocolateyPackages#5]
Since this morning `cup -y VirtualBox.ExtensionPack` reports:
```console
ERROR: Checksum for 'C:\...\Temp\VirtualBox.ExtensionPack\Oracle_VM_VirtualBox_Extension_Pack-5.1.10-112026.vbox-extpack' did not meet '82C6AE207BB8CC9D6FD6DB09D99825D0ECF0473A85A5CA98A2F1A0D06E42D6F3' for checksum type 'sha256'.
```

**Comment by michaelray** [comment]
Fixed in VirtualBox.ExtensionPack v5.1.10.112026 by https://github.com/michaelray/ChocolateyPackages/commit/d25d3e90aed71deac78a33a3889f23c18ab3b3c8

It looks like the Oracle/VB folks changed the file after initially releasing it.  The checksum was correct when it was packaged... it even passed the automated testing, which shows the checksum matched.

Thanks for submitting an issue to let me know, though.
